### ISSUE TITLE
High-CPU use (probably from file sources)

### ISSUE THREAD

**Issue by blt** [postmates/cernan#191]
I've noticed high-cpu use when file sources are enabled and there's no files to feed them, not even the right directories. This has not been observed on production systems so it's _possible_ this is some combination of OSX and a debug build. 

Configuration is:

```toml
data-directory = "data/"
scripts-directory = "examples/scripts/"

flush-interval = 5

[tags]
source = "cernan"

[sources]
  [sources.statsd.primary]
  enabled = false
  port = 8125
  forwards = ["sinks.console", "sinks.null", "sinks.influxdb", "sinks.prometheus"]

  [sources.native]
  ip = "127.0.0.1"
  port = 1972
  forwards = ["sinks.console", "sinks.null", "sinks.influxdb", "sinks.prometheus"]

  [sources.graphite.primary]
  enabled = false
  port = 2004
  forwards = ["filters.collectd_scrub"]

  [sources.files]
  [sources.files.example_log]
  path = "example.log"
  forwards = ["sinks.firehose.stream_two"]

  [sources.files.foo_log]
  path = "foo.log"
  forwards = ["sinks.firehose.stream_two"]

[filters]
  [filters.collectd_scrub]
  script = "collectd_scrub.lua"
  forwards = ["sinks.console", "sinks.null", "sinks.influxdb", "sinks.prometheus"]

[sinks]
  [sinks.console]
  bin_width = 1

  [sinks.null]

  # [sinks.wavefront]
  # port = 2878
  # host = "127.0.0.1"
  # bin_width = 1

  [sinks.influxdb]
  port = 8089
  host = "127.0.0.1"
  bin_width = 1

  [sinks.prometheus]
  port = 8080
  host = "127.0.0.1"
  bin_width = 1

  [sinks.firehose.stream_two]
  delivery_stream = "stream_two"
  batch_size = 800
  region = "us-east-1"
```

No change has been made to the lua filter. There's no traffic coming into the system, this is an idle problem.
