### ISSUE TITLE
filters can't forward into filters

### ISSUE THREAD

**Issue by blt** [postmates/cernan#226]
Hey so here's a fun one. Consider this setup:

```toml
[filters]
  [filters.zero_insert]
  script = "zero_insert.lua"
  forwards = ["sinks.console"]

  [filters.collectd_scrub]
  script = "collectd_scrub.lua"
  forwards = ["filters.zero_insert"]
```

What's expected is that `collectd_scrub` ought to forward into `zero_insert` -- see #225 -- but instead we find that

```
[cernan][77][2017-03-07T21:36:25.019832+00:00][INFO] cernan - 0.5.5
[cernan][36][2017-03-07T21:36:25.020361+00:00][ERROR] Unable to fulfill configured forward: filters.collectd_scrub => filters.zero_insert
```

Oops!
