### ISSUE TITLE
Support HISTOGRAM in statsd source

### ISSUE THREAD

**Issue by blt** [postmates/cernan#307]
As discussed in #290 we want to expose using HISTOGRAM as the basis for statsd histogram / timer. The discussion in that issue didn't really come to a consensus on how we want to achieve this. Of note: 

  * individual cernans cannot dynamically choose bin totals / widths (doing so breaks aggregation in multi-cernan environments)
  * extending the protocol to add bin totals / widths is a real pain 

My inclination is to follow the lead of etsy/statsd and allow the statsd source to be configured with: 

  * a generic, one-size-fits-all configuration 
  * specific configuration decided by metric name

When a new line comes through the source, the specific configuration is used if the name hits, else we use the generic. 

@bitglue @tfheen @tsantero any thoughts / concerns?

**Comment by bitglue** [comment]
I guess I wonder if histograms in statsd are worth the effort, or if it's better to just use Prometheus or some other protocol if histograms are desired. While it's theoretically possible to configure the histogram bins based on metric name, in practice it's just a pain and I bet the result is just a lot of extra datapoints being sent with little value. With Prometheus the bin configuration is within the application logic so configuration is much easier.

**Comment by benley** [comment]
I think it would be nice to actually implement this, even if you have to configure the bin thresholds for each metric that uses it.

The prometheus statsd_exporter uses a config file to spell it all out, e.g.

```yaml
defaults:
  timer_type: histogram
  buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5 ]
mappings:
# This will be a histogram using the buckets set in `defaults`.
- match: test.timing.*.*.*
  labels: 
    name: "my_timer"
    provider: "$2"
    outcome: "$3"
    job: "${1}_server"
# This will be a summary timer.
- match: other.timing.*.*.*
  timer_type: summary
  labels: 
    name: "other_timer"
    provider: "$2"
    outcome: "$3"
    job: "${1}_server_other"
```

(from [the docs](https://github.com/prometheus/statsd_exporter#metric-mapping-and-configuration))

Since it is [impossible to meaningfully aggregate quantile metrics](https://www.vividcortex.com/blog/why-percentiles-dont-work-the-way-you-think), it seems preferable to store data in binned histograms wherever possible instead of internally converting it to quantiles.

<img width="431" alt="if you think you can average percentiles" src="https://user-images.githubusercontent.com/1432730/30724610-fdfce968-9f0c-11e7-9434-83ff37384456.png">
